#!/bin/bash

# Brew
system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  if [ -f "$HOME/.config/brew/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file="$HOME/.config/brew/Brewfile"
  fi

fi

# iterm2
# ref: https://shyr.io/blog/sync-iterm2-configs
defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true


# Install Volta and deps
brew install volta

volta install node
volta install yarn
volta install fkill-cli

# reload bat with themes
bat cache --build

# Activate zsh
chsh -s $(which zsh)
