# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.dft]
local = "~/.config/zsh/plugins/dft"
apply = ["source"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.fzf-git]
github = "junegunn/fzf-git.sh"

# Completion plugins, see (zsh/completion.zsh for more info)

# [plugins.zsh-autocomplete]
# github = "marlonrichert/zsh-autocomplete"

# [plugins.fzf-tab-completion]
# github = "lincheney/fzf-tab-completion"
# use = ["zsh/fzf-zsh-completion.sh"]
# apply = []

# [plugins.fzf-tab]
# github = "Aloxaf/fzf-tab"
# apply = []
