#!/usr/bin/env bash

echo "Installing homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install yadm

echo "Installing dotfiles"
yadm clone https://github.com/gossi/dotfiles.git --no-botstrap

# check if class is available and set it
if [ $# -gt 0 ]; then
  yadm config local.class $1
fi

# let yadm do the rest
yadm alt
yadm bootstrap
